---
# stackconfig.yaml - ruby-awstools configuration and parameters for the
# core IAM and Logging templates, derived from the AWS NIST Quickstart
MainTemplate:
  File: main.yaml
  Format: yaml
  StackName: RefCore
IamTemplate:
  File: iam.yaml
  Format: yaml
  # ... final stack name will be <StackFamily>-NISTcore-IAMStack-<random>
LoggingTemplate:
  File: logging.yaml
  Format: yaml
Parameters:
  pNotifyEmail: <REQUIRED> # Raise exception if no override
