---
# stackconfig.yaml - ruby-awstools configuration and parameters for the
# core IAM and Logging templates, derived from the AWS NIST Quickstart
MainTemplate: main.yaml
StackName: RefCore
ChildStacks:
- iam.yaml
- logging.yaml
Parameters:
  pNotifyEmail: ${&NotifyMail} # All cloudconfig.yaml references are required
