---
# CloudGenerator Intranet subnets ACL template
#
# This was created based on the AWS 'Scenario 2':
# http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html
AWSTemplateFormatVersion: '2010-09-09'
Description: The Intranet subnet ACLs
Parameters:
  VPCId: { Type: String }
  IntranetAcl: { Type: String }

# Note that with CG, only ids of created resources need to be passed in
# as parameters.
# Parameters: (none needed, top-level resource)
Resources:
### NetworkAcls
# Acl's for the Intranet subnets

## IntranetInboundAcls
  # Note that even for Intranet, SSH is still restricted to Org CIDRs and
  # the Management subnet
  InboundIntranetAllowOrgSSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 100
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 22, To: 22 }
      CidrBlock: { Ref: $OrgCIDRs }

  InboundIntranetAllowSSHManagement:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 110
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 22, To: 22 }
      CidrBlock: { Ref: $ManagementSubnet }

  # Similar restrictions for RDP
  InboundIntranetAllowOrgRDP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 120
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 3389, To: 3389 }
      CidrBlock: { Ref: $OrgCIDRs }

  InboundIntranetAllowRDPManagement:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 130
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 3389, To: 3389 }
      CidrBlock: { Ref: $ManagementSubnet }

  InboundIntranetAllowHttpOrg:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 200
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 80, To: 80 }
      CidrBlock: { Ref: $OrgCIDRs }

  InboundIntranetAllowHttpsOrg:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 210
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 443, To: 443 }
      CidrBlock: { Ref: $OrgCIDRs }

  InboundIntranetAllowHttpVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 220
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 80, To: 80 }
      CidrBlock: { Ref: $VPCCIDR }

  InboundIntranetAllowHttpsVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 230
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 443, To: 443 }
      CidrBlock: { Ref: $VPCCIDR }

  InboundNetworkAclAllowReturn:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 250
      RuleAction: allow
      Protocol: 6
      Egress: false
      # Allow return traffic to ephemeral ports created by
      # outbound connections.
      PortRange: { From: 32768, To: 65535 }
      CidrBlock: 0.0.0.0/0

## End IntranetInboundAcls
## IntranetOutboundAcls

  # Allow sending email
  OutboundIntranetAllowSmtp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 100
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 25, To: 25 }
      CidrBlock: 0.0.0.0/0

  OutboundIntranetAllowMailSub:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 110
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 587, To: 587 }
      CidrBlock: 0.0.0.0/0

  # Allow outbound connections to http/s
  OutboundIntranetAllowHttp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 120
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 80, To: 80 }
      CidrBlock: 0.0.0.0/0

  OutboundIntranetAllowHttps:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 130
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 443, To: 443 }
      CidrBlock: 0.0.0.0/0
  
  # Allow DB Connections to Private
  OutboundIntranetAllowPostgreSQL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 140
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 5432, To: 5432 }
      CidrBlock: { Ref: $PrivateSubnet }
  
  OutboundIntranetAllowMSSQL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 150
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 1433, To: 1433 }
      CidrBlock: { Ref: $PrivateSubnet }
  
  OutboundIntranetAllowMySQL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 160
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 3306, To: 3306 }
      CidrBlock: { Ref: $PrivateSubnet }
  
  OutboundNetworkAclAllowReturn:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: IntranetAcl }
      RuleNumber: 200
      RuleAction: allow
      Protocol: 6
      Egress: true
      # Allow return traffic to connecting clients
      PortRange: { From: 32768, To: 65535 }
      CidrBlock: 0.0.0.0/0

## End IntranetOutboundAcls
### End NetworkAcls
