---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud main template
Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
  
  PublicAclStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: { "Fn::GetAtt": [ "VPCStack", "Outputs.VPCId" ] }
        PublicAcl: { "Fn::GetAtt": [ "VPCStack", "Outputs.PublicAcl" ] }

  PrivateAclStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: { "Fn::GetAtt": [ "VPCStack", "Outputs.VPCId" ] }
        PrivateAcl: { "Fn::GetAtt": [ "VPCStack", "Outputs.PrivateAcl" ] }

  IntranetAclStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: { "Fn::GetAtt": [ "VPCStack", "Outputs.VPCId" ] }
        IntranetAcl: { "Fn::GetAtt": [ "VPCStack", "Outputs.IntranetAcl" ] }

  ManagementAclStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: { "Fn::GetAtt": [ "VPCStack", "Outputs.VPCId" ] }
        ManagementAcl: { "Fn::GetAtt": [ "VPCStack", "Outputs.ManagementAcl" ] }

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCId: { "Fn::GetAtt": [ "VPCStack", "Outputs.VPCId" ] }

# cfngenerate will add Outputs for each child stack, but for convenience
# you can put other outputs here. Note that there's a limit of 60 outputs
# per stack, so it's probably not feasible to gather all the outputs here.
# More likely output lookups will be two-step:
# 1) Look up the parent stack (e.g. VPCStack)
# 2) Look up the output from that stack (e.g. PublicSubnetA)
Outputs:
  VPCId:
    Description: VPCId of the newly created VPC
    Value: { "Fn::GetAtt": [ "VPCStack", "Outputs.VPCId" ] }
