---
# CloudGenerator network template, used to generate the VPC and subnets
#
# This was created based on the AWS 'Scenario 2':
# http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html
AWSTemplateFormatVersion: '2010-09-09'
Description: The Private subnet ACLs
Parameters:
  VPCId: { Type: String }
  PrivateAcl: { Type: String }

# Note that with CG, only ids of created resources need to be passed in
# as parameters.
# Parameters: (none needed, top-level resource)
Resources:
### PrivateAcls
# Acl's for the Private subnets

## PrivateInboundAcls
  # Note that even for Private, SSH is still restricted to Org CIDRs and
  # the Management subnet
  InboundPrivateAllowOrgSSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 100
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 22, To: 22 }
      CidrBlock: { Ref: $OrgCIDRs }

  InboundPrivateAllowSSHManagement:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 110
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 22, To: 22 }
      CidrBlock: { Ref: $ManagementSubnet }

  # Similar restrictions for RDP
  InboundPrivateAllowOrgRDP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 120
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 3389, To: 3389 }
      CidrBlock: { Ref: $OrgCIDRs }

  InboundPrivateAllowRDPManagement:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 130
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 3389, To: 3389 }
      CidrBlock: { Ref: $ManagementSubnet }

  # Allow DB Connections from VPC
  InboundPrivateAllowPostgreSQL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 140
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 5432, To: 5432 }
      CidrBlock: { Ref: $VPCCIDR }
  
  InboundPrivateAllowMSSQL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 150
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 1433, To: 1433 }
      CidrBlock: { Ref: $VPCCIDR }
  
  InboundPrivateAllowMySQL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 160
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 3306, To: 3306 }
      CidrBlock: { Ref: $VPCCIDR }
  
  # Allow http/s for e.g. back-end web services
  InboundPrivateAllowHttp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 200
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 80, To: 80 }
      CidrBlock: 0.0.0.0/0

  InboundPrivateAllowHttps:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 210
      RuleAction: allow
      Protocol: 6
      Egress: false
      PortRange: { From: 443, To: 443 }
      CidrBlock: 0.0.0.0/0

  InboundPrivateAclAllowReturn:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 250
      RuleAction: allow
      Protocol: 6
      Egress: false
      # Allow return traffic to ephemeral ports created by
      # outbound connections.
      PortRange: { From: 32768, To: 65535 }
      CidrBlock: 0.0.0.0/0

## End PrivateInboundAcls
## PrivateOutboundAcls

  # Allow outbound connections to http/s for e.g. getting OS updates;
  # requires a NAT gateway/instance
  OutboundPrivateAllowHttp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 120
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 80, To: 80 }
      CidrBlock: 0.0.0.0/0

  OutboundPrivateAllowHttps:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 130
      RuleAction: allow
      Protocol: 6
      Egress: true
      PortRange: { From: 443, To: 443 }
      CidrBlock: 0.0.0.0/0
  
  OutboundPrivateAclAllowReturn:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: { Ref: PrivateAcl }
      RuleNumber: 200
      RuleAction: allow
      Protocol: 6
      Egress: true
      # Allow return traffic to connecting clients
      PortRange: { From: 32768, To: 65535 }
      CidrBlock: 0.0.0.0/0

## End PrivateOutboundAcls
### End PrivateAcls
