---
AWSTemplateFormatVersion: '2010-09-09'
Description: Servers

# NOTE: Outputs from SecurityGroups stack passed in from main stack
# as parameters

Resources:
  StudioOneData:
    Type: 'AWS::EC2::Volume'
    # If the stack is deleted, a snapshot will be created
    DeletionPolicy: Snapshot
    Properties:
      AvailabilityZone: us-east-1b
      Encrypted: true
      # In gigabytes
      Size: 50
      VolumeType: standard
      Tags:
      - Name: StudioOneData

  StudioOne:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-6d1c2007 # CentOS-7 x64 with updates, HVM

      SecurityGroups:
      - Ref: SSHAccessIT
      - Ref: PublicWebServer
