---
# NIST stackconfig.yaml - ruby-awstools configuration and parameters for the
# AWS NIST quickstart stack, non-govcloud.
StackName: NISTcore
MainTemplate:
  File: main.template
  Format: yaml
IamTemplate:
  File: iam.template
  Format: yaml
LoggingTemplate:
  File: logging.template
  Format: yaml
Parameters:
  pNotifyEmail: <REQUIRED> # Raise exception if no override
  pAvailabilityZoneA: <REQUIRED> # e.g. us-east-1c
  pAvailabilityZoneB: <REQUIRED> # e.g. us-east-1d
