---
# NIST stackconfig.yaml - ruby-awstools configuration and parameters for the
# AWS NIST quickstart stack, non-govcloud.
MainTemplate:
  File: main.template
  Format: yaml
  StackName: NISTcore
IamTemplate:
  File: iam.template
  Format: yaml
  # ... final stack name will be <StackFamily>-NISTcore-IAMStack-<random>
LoggingTemplate:
  File: logging.template
  Format: yaml
Parameters:
  pNotifyEmail: <REQUIRED> # Raise exception if no override
  pAvailabilityZoneA: <REQUIRED> # e.g. us-east-1c
  pAvailabilityZoneB: <REQUIRED> # e.g. us-east-1d
