---
# cloudconfig.yaml - central config file for ruby-awstools library

### Library definitions - values used internally by ruby-awstools
# Where to search for common definitions
#SearchPath:
#- /path/to/examples/WebDBScalableVPC

## CloudFormation (cfn tool)
# S3 bucket where CloudFormation templates will go
#Bucket: cfn.linuxjedi
# Prefix for CloudFormation templates, templates will go in
# s3://bucket/<prefix>/<dirname>/<filename>
Prefix: us-east-1
# Optional prefix for stack names
#StackFamily: Central

Region: us-east-1
# Common tags to be applied to any resources created, commonly for billing tags
#Tags:
#- Project: WebEnvironment

# Not all availability zones are available for a given account, so check
# first with 'aws ec2 describe-availability-zones', then list the ones
# you want to use here.
AvailabilityZones: [ "a", "b", "c", "d" ]

### Other configuration variables - referenced in templates but not the library
# Lists of CIDRs can be referenced in ACLs using Ref:\n"$<somelist>". See
# the vpc templates for examples. Acls will be expanded as needed.
#
# IP Ranges for your organization, used for access to e.g. Intranet
# and Management subnets.
ISPCIDRs:
- 76.0.0.0/13 # CenturyLink
# VPC CIDR, encompassing the entirety of the cloud network; this should
# probably be a class-B network from somewhere in RFC 1918
VPCCIDR: 10.20.0.0/16
# AWS hosted public DNS
PublicDNS: "linuxjedi.org"
# Instances in the VPC will resolve hostnames to the private zone and
# get VPC-internal addresses
PrivateDNS: "linuxjedi.org"
# Each subnet type corresponds to a Subnet declaration in the network
# template. Each subnet type will be duplicated across all availability
# zones, so you'll need to provide a number of subnets equal to the
# availability zones, all within the overall CIDR for the type.
SubnetTypes:
  vpc-one:
    # Public subnets for providing services to the Whole Wide World
    PublicSubnet:
      CIDR: 10.20.128.0/17
      Subnets: [ "10.20.128.0/20", "10.20.144.0/20", "10.20.160.0/20", "10.20.176.0/20" ]
    # Private subnets providing services mainly to hosts in Public
    PrivateSubnet:
      CIDR: 10.20.32.0/19
      Subnets: [ "10.20.32.0/22", "10.20.36.0/22", "10.20.40.0/22", "10.20.44.0/22" ]
