---
# stackconfig.yaml - ruby-awstools configuration and parameters for a
# Management VPC from the Reference Architecture
MainTemplate: vpc-management.yaml
StackName: MgmtVPC
ChildStacks:
- securitygroups.yaml
Parameters:
  # pEnvironment: Production
  # pCreateNatGateway: false # default, set true for a NAT Gateway
  pManagementCIDR: ${&MgmtCIDR}
  pManagementDMZSubnetACIDR: ${&MgmtDMZACIDR}
  pManagementDMZSubnetBCIDR: ${&MgmtDMZBCIDR}
  pManagementPrivateSubnetACIDR: ${&MgmtPVTACIDR}
  pManagementPrivateSubnetBCIDR: ${&MgmtPVTBCIDR}
  pManagementBastionAccessCIDR: ${&MgmtBastionAccessCIDR}
  pRegionAZ1Name: ${&RegionAZ1}
  pRegionAZ2Name: ${&RegionAZ2}
  pS3URLprefix: ${@s3urlprefix}
