---
# stackconfig.yaml - ruby-awstools configuration and parameters for a
# Management VPC from the Reference Architecture
MainTemplate:
  File: vpc-management.yaml
  Format: yaml
  StackName: MgmtVPC
Parameters:
  # pEnvironment: Production
  # pCreateNatGateway: false # default, set true for a NAT Gateway
  pManagementCIDR: ${&MgmtCIDR}
  pManagementDMZSubnetACIDR: ${&MgmtDMZACIDR}
  pManagementDMZSubnetBCIDR: ${&MgmtDMZBCIDR}
  pManagementPrivateSubnetACIDR: ${&MgmtPVTACIDR}
  pManagementPrivateSubnetBCIDR: ${&MgmtPVTBCIDR}
  pRegionAZ1Name: ${&RegionAZ1}
  pRegionAZ2Name: ${&RegionAZ2}
